# Generated by Django 6.1 on 2026-08-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Unique identifier for the feature flag (e.g., 'NEW_CHECKOUT_FLOW').", max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Master toggle: False (Kill switch, always OFF), True (Live, evaluates conditions or ON for all if empty).')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Targeting rules, user groups, or rollout percentages.')),
                ('variants', models.JSONField(blank=True, help_text='A/B/N testing variants and payloads.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
            },
        ),
    ]
